const styles = {
  container: {
    display: "flex",
    fontFamily: "Arial, sans-serif",
    backgroundColor: "#e8f2ec",
    height: "100vh",
    overflow: "hidden",
    width: "100%",
  },
  sidebar: {
    width: "70px",
    backgroundColor: "white",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "20px 0",
    boxShadow: "2px 0 5px rgba(0,0,0,0.1)",
  },
  profileCircle: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#f0f0f0",
    marginBottom: "30px",
  },
  sidebarIcons: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    flex: 1,
  },
  iconBox: {
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "20px",
    color: "#888",
  },
  activeIcon: {
    backgroundColor: "#e8f2ec",
    borderRadius: "10px",
    color: "#4CAF50",
    padding: "8px",
  },
  bottomCircle: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#f0f0f0",
    marginTop: "30px",
  },
  mainContent: {
    flex: 1,
    padding: "20px",
    overflowY: "auto",
  },
  header: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    marginBottom: "20px",
  },
  searchBar: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: "25px",
    padding: "5px",
    width: "300px",
  },
  searchInput: {
    border: "none",
    outline: "none",
    flex: 1,
    padding: "8px 15px",
    fontSize: "14px",
    backgroundColor: "transparent",
  },
  dropdownButton: {
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    fontSize: "12px",
    color: "#888",
    padding: "0 15px",
  },
  sectionTitle: {
    fontSize: "22px",
    fontWeight: "600",
    marginBottom: "20px",
    color: "#333",
  },
  statsCards: {
    display: "flex",
    gap: "20px",
    marginBottom: "20px",
  },
  statCard: {
    backgroundColor: "white",
    borderRadius: "15px",
    padding: "20px",
    display: "flex",
    alignItems: "center",
    flex: 1,
    boxShadow: "0 2px 5px rgba(0,0,0,0.05)",
  },
  iconCircle: {
    width: "45px",
    height: "45px",
    borderRadius: "50%",
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: "15px",
    fontSize: "20px",
    color: "#4CAF50",
  },
  statInfo: {
    flex: 1,
  },
  statValue: {
    fontSize: "22px",
    fontWeight: "bold",
    margin: "0",
    color: "#333",
  },
  statLabel: {
    fontSize: "12px",
    color: "#888",
    margin: "5px 0 0 0",
  },
  chartsRow: {
    display: "flex",
    gap: "20px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  orderSummary: {
    backgroundColor: "white",
    borderRadius: "15px",
    padding: "20px",
    flex: "1 1 30%",
    boxShadow: "0 2px 5px rgba(0,0,0,0.05)",
    minWidth: "300px",
  },
  revenueChart: {
    backgroundColor: "white",
    borderRadius: "15px",
    padding: "20px",
    flex: "1 1 30%",
    boxShadow: "0 2px 5px rgba(0,0,0,0.05)",
    minWidth: "300px",
  },
  tablesCard: {
    backgroundColor: "white",
    borderRadius: "15px",
    padding: "20px",
    flex: "1 1 30%",
    boxShadow: "0 2px 5px rgba(0,0,0,0.05)",
    minWidth: "300px",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "20px",
  },
  cardTitle: {
    fontSize: "18px",
    fontWeight: "600",
    margin: "0 0 5px 0",
    color: "#333",
  },
  cardSubtitle: {
    fontSize: "10px",
    color: "#aaa",
    margin: "0",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "200px",
  },
  periodSelector: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "white",
    border: "1px solid #eee",
    borderRadius: "20px",
    padding: "5px 15px",
    fontSize: "14px",
    color: "#666",
  },
  dropdownArrow: {
    fontSize: "10px",
    marginLeft: "10px",
  },
  orderNumbers: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "20px",
  },
  orderNumber: {
    textAlign: "center",
    backgroundColor: "white",
    borderRadius: "8px",
    padding: "10px 15px",
    border: "1px solid #eee",
    flex: "1",
    margin: "0 5px",
  },
  orderValue: {
    fontSize: "18px",
    fontWeight: "bold",
    margin: "0",
    color: "#333",
  },
  orderType: {
    fontSize: "12px",
    color: "#888",
    margin: "5px 0 0 0",
  },
  pieChartContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  pieChart: {
    width: "150px",
    height: "150px",
    borderRadius: "50%",
    position: "relative",
    overflow: "hidden",
    background: "#ddd",
    marginBottom: "20px",
  },
  pieSlice1: {
    position: "absolute",
    width: "100%",
    height: "100%",
    clip: "rect(0, 150px, 75px, 0)",
    background: "#555",
    transform: "rotate(0deg)",
  },
  pieSlice2: {
    position: "absolute",
    width: "100%",
    height: "100%",
    clip: "rect(0, 75px, 150px, 0)",
    background: "#888",
    transform: "rotate(90deg)",
  },
  pieSlice3: {
    position: "absolute",
    width: "100%",
    height: "100%",
    clip: "rect(75px, 150px, 150px, 0)",
    background: "#aaa",
    transform: "rotate(180deg)",
  },
  pieChartLegend: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
  },
  legendColor1: {
    width: "15px",
    height: "5px",
    backgroundColor: "#555",
    marginRight: "10px",
  },
  legendColor2: {
    width: "15px",
    height: "5px",
    backgroundColor: "#888",
    marginRight: "10px",
  },
  legendColor3: {
    width: "15px",
    height: "5px",
    backgroundColor: "#aaa",
    marginRight: "10px",
  },
  legendText: {
    fontSize: "12px",
    color: "#555",
    flex: 1,
  },
  legendPercent: {
    fontSize: "12px",
    color: "#888",
  },
  lineChart: {
    width: "100%",
  },
  chart: {
    width: "100%",
    height: "200px",
  },
  chartLabels: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "10px",
    fontSize: "12px",
    color: "#888",
  },
  tableLegend: {
    display: "flex",
    gap: "20px",
    marginBottom: "15px",
  },
  reservedIndicator: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#4CAF50",
    marginRight: "5px",
  },
  availableIndicator: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "white",
    border: "1px solid #ddd",
    marginRight: "5px",
  },
  tablesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: "10px",
  },
  tableBox: {
    borderRadius: "8px",
    border: "1px solid #eee",
    padding: "5px",
    textAlign: "center",
    fontSize: "12px",
  },
  tableTop: {
    fontSize: "10px",
  },
  tableNumber: {
    fontWeight: "bold",
    fontSize: "16px",
  },
  chefTable: {
    backgroundColor: "white",
    borderRadius: "15px",
    padding: "20px",
    boxShadow: "0 2px 5px rgba(0,0,0,0.05)",
  },
  tableHeader: {
    display: "flex",
    backgroundColor: "#f9f9f9",
    padding: "10px 15px",
    borderRadius: "8px 8px 0 0",
    fontWeight: "bold",
    color: "#333",
  },
  headerCell: {
    flex: 1,
    fontSize: "16px",
  },
  tableRow: {
    display: "flex",
    padding: "15px",
    borderBottom: "1px solid #eee",
  },
  tableCell: {
    flex: 1,
    fontSize: "14px",
    color: "#555",
  },
};

export default styles;
